https://studywolf.wordpress.com/2012/09/14/cython-journey-part-1/

python setup.py build_ext -i

Troubleshooting:

-----------------------------------------------------

* Forgetting to mention a file in sources in setup.py results in error like:

ImportError: /home/pth/git/magnum.af/interface/magnum_af.so: undefined symbol: _ZN4MeshC1Eiiiddd

Include respective file in src/CMakeLists cython_add_module_w_AF_VTK() to solve

-----------------------------------------------------

* Core dump at startup often results when choosing the wrong library in setup.py for desired backend (cpu, opencl, cuda)

E.g.: ibraries = ["afopencl"] 

Include correct library in setup.py

-----------------------------------------------------

* af JIT error:

Error message:

terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function std::vector<char> cuda::compileToPTX(const char*, std::string)
In file src/backend/cuda/jit.cpp:291
NVRTC Error(6): NVRTC_ERROR_COMPILATION

Fix:
include af::eval() in respective function/line where program crashes


-----------------------------------------------------

* af Memory error:

https://github.com/arrayfire/arrayfire/issues/1709

Fix:
remove af.lock() or af device pointer 
optionally add more af::eval()


-----------------------------------------------------

Error:
/usr/local/lib/libafopencl.so.3.5.0: undefined reference to `clReleaseMemObject@OPENCL_1.0'
Fix:
Include 
        ${OpenCL_LIBRARIES} #TODO include this on eg GTO
in src/CMakeLists.txt

Tower Only:
Suddenly lost internet connectivity
Fixed by adding another ethernet network: Edit Connections -> Add -> Choose Ethernet and Create... -> Save (only defaults, omitting a name)

-----------------------------------------------------
-----------------------------------------------------
Wrapping:

"Segmentation fault (core dumped)" occurs when a cpp-function writes to cout!!!


-----------------------------------------------------
Wrapping:

Traceback (most recent call last):
  File "stress.py", line 6, in <module>
    from magnum_af import *
ImportError: dynamic module does not define init function (PyInit_magnum_af)

when called with python3 on GTO

Temp fix: calling with python or python2 runns
Guess: cmake, cython messing around with python versions?
